# Generated by Django 4.1 on 2022-11-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="phone",
            field=models.TextField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="time_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="picture",
            field=models.TextField(blank=True, null=True),
        ),
    ]
