# Generated by Django 4.1 on 2022-11-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_facility_floor_facility_phone_facility_time_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
    ]
